# Scratch

https://peterbloem.nl/blog/transformers

In [2]:
import torch
import torch.nn.functional as F

In [4]:
x = torch.randn(2, 3, 4)
x

tensor([[[-0.9392,  0.8711,  1.2642, -0.3693],
         [-0.3113,  0.4527,  0.1538, -0.4229],
         [ 1.6715, -0.4245,  0.6328, -1.6786]],

        [[ 1.9856, -1.3506, -0.2016,  1.4776],
         [-1.3720,  0.6707,  0.0228,  1.8053],
         [ 1.3059,  0.9915, -0.5044, -1.4064]]])

In [5]:
x.transpose(1, 2)

tensor([[[-0.9392, -0.3113,  1.6715],
         [ 0.8711,  0.4527, -0.4245],
         [ 1.2642,  0.1538,  0.6328],
         [-0.3693, -0.4229, -1.6786]],

        [[ 1.9856, -1.3720,  1.3059],
         [-1.3506,  0.6707,  0.9915],
         [-0.2016,  0.0228, -0.5044],
         [ 1.4776,  1.8053, -1.4064]]])

In [6]:
raw_weights = torch.bmm(x, x.transpose(1, 2))
raw_weights

tensor([[[ 3.3756,  1.0374, -0.5198],
         [ 1.0374,  0.5044,  0.0947],
         [-0.5198,  0.0947,  6.1922]],

        [[ 7.9906, -0.9671, -0.7225],
         [-0.9671,  5.5919, -3.6771],
         [-0.7225, -3.6771,  4.9208]]])

In [7]:
weights = F.softmax(raw_weights, dim=2)
weights

tensor([[[8.9539e-01, 8.6406e-02, 1.8208e-02],
         [5.0596e-01, 2.9692e-01, 1.9712e-01],
         [1.2121e-03, 2.2408e-03, 9.9655e-01]],

        [[9.9971e-01, 1.2870e-04, 1.6436e-04],
         [1.4151e-03, 9.9849e-01, 9.4163e-05],
         [3.5278e-03, 1.8381e-04, 9.9629e-01]]])

In [8]:
weights.sum()

tensor(6.)

In [9]:
8.9539e-01 + 8.6406e-02 + 1.8208e-02

1.000004

In [11]:
y = torch.bmm(weights, x)
y

tensor([[[-0.8374,  0.8114,  1.1568, -0.3978],
         [-0.2381,  0.4915,  0.8101, -0.6433],
         [ 1.6639, -0.4209,  0.6325, -1.6742]],

        [[ 1.9851, -1.3500, -0.2016,  1.4771],
         [-1.3670,  0.6679,  0.0224,  1.8046],
         [ 1.3078,  0.9832, -0.5033, -1.3956]]])

In [12]:
x

tensor([[[-0.9392,  0.8711,  1.2642, -0.3693],
         [-0.3113,  0.4527,  0.1538, -0.4229],
         [ 1.6715, -0.4245,  0.6328, -1.6786]],

        [[ 1.9856, -1.3506, -0.2016,  1.4776],
         [-1.3720,  0.6707,  0.0228,  1.8053],
         [ 1.3059,  0.9915, -0.5044, -1.4064]]])